/*
 * InformationForm.java
 *
 * Created on October 1, 2004, 9:22 AM
 */

package dpm.dpmApp.desktop.forms;

import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.DpmTerms;
import dpm.peer.Peer;
import java.text.DateFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JTextPane;
import javax.swing.text.*;



/**
 *
 * @author  cumming
 */
public class InformationForm extends JFrame implements DpmTerms {
    protected DpmAppTopFrame topFrame;
    protected Peer appUser;    
    protected static DateFormat dateFormat =
    DateFormat.getDateTimeInstance(DateFormat.DEFAULT, DateFormat.DEFAULT, Locale.US);
    
    /** Creates new form InformationForm */
    public InformationForm(DpmAppTopFrame topFrame) {
        this.topFrame = topFrame;
        this.appUser = topFrame.getAppUser();   
        initComponents();
    }    
    
    public StyledDocument insert(String content, StyledDocument doc, String style) {
        try {
            doc.insertString(doc.getLength(), content, doc.getStyle(style));
        }
        catch (BadLocationException e) {
            e.printStackTrace();
        }
        return doc;
    }
    
    protected void addStylesToDocument(StyledDocument doc) {
        //Initialize some styles.
        Style def = StyleContext.getDefaultStyleContext().getStyle(StyleContext.DEFAULT_STYLE);
        StyleConstants.setFontFamily(def, "SansSerif");
        
        Style regular = doc.addStyle(REGULAR, def);
        
        Style s = doc.addStyle(ITALIC, regular);
        StyleConstants.setItalic(s, true);
        
        s = doc.addStyle(BOLD, regular);
        StyleConstants.setBold(s, true);
        
        s = doc.addStyle(SMALL, regular);
        StyleConstants.setFontSize(s, 10);
        
        s = doc.addStyle(LARGE, regular);
        StyleConstants.setFontSize(s, 16);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    //    public static void main(String args[]) {
    //        new InformationForm().addDpmMessage();
    //    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
