/*
 * InputForm.java
 *
 * Created on December 31, 2003, 9:20 AM
 */

package dpm.dpmApp.desktop.forms;

import dpm.content.ContentStorage;
import dpm.dpmApp.desktop.DpmTerms;
import dpm.dpmApp.desktop.subpages.PeerGroupsTreePage;
import dpm.peer.Peer;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import java.text.DateFormatSymbols;
import dpm.content.advertisement.AdvUtilities;
import dpm.content.advertisement.designEntity.UserNamedEntityAdv;
import dpm.content.advertisement.net.LoopNetAdvertisement;
import dpm.content.state.DesignEntityInputPolicy;
import dpm.content.state.LoopNetReader;
import dpm.content.state.policy.SimpleInputPolicy;
import dpm.dpmApp.desktop.DpmAppTopFrame;
import java.util.*;
import javax.swing.*;
import net.jxta.peergroup.PeerGroup;
import dpm.dpmApp.desktop.forms.*;
import dpm.dpmApp.desktop.forms.input.panels.*;


/** The user input form for new Tasks that is: TaskAdvertisements.
 * @author cumming
 * @since December 31, 2003, 9:20 AM
 */
public abstract class InputForm extends JFrame implements DpmTerms {
    protected PeerGroup parentPG;
    protected DpmAppTopFrame topFrame;
    protected Peer appUser;
    protected AdvUtilities advUtils;
    
    
    /** Creates new form NewForm */
    public InputForm(PeerGroup parentPG, DpmAppTopFrame topFrame) {
        this.parentPG = parentPG;
        this.topFrame = topFrame;
        this.appUser = topFrame.getAppUser();
        this.advUtils = topFrame.getAdvUtils();       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setName("NewTaskFormFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
