/*
 * NewChatMessageForm.java
 *
 * Created on September 24, 2004, 2:20 PM
 */

package dpm.dpmApp.desktop.forms.messages;

import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.forms.MessageForm;
import net.jxta.peergroup.PeerGroup;


/**
 *
 * @author  cumming
 */
public class NewChatMessageForm extends MessageForm {
    
    /** Creates new form NewChatMessageForm */
    public NewChatMessageForm(PeerGroup parentPG, DpmAppTopFrame topFrame) {
        super(parentPG, topFrame);
        
        initComponents();
        messageTextPanel.setBackground(USER_INPUT_COLOR);
        setTitle("Post message to peergroup: " + parentPG.getPeerGroupName());
        topFrame.setPosition(this.getWidth(), this.getHeight(), this);
        pack();
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        messagePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        messageTextPanel = new javax.swing.JTextArea();
        buttonsPanel = new javax.swing.JPanel();
        postMessageButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        scrollPane.setFont(new java.awt.Font("Arial", 0, 12));
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 100));
        messageTextPanel.setBackground(new java.awt.Color(204, 255, 204));
        messageTextPanel.setFont(new java.awt.Font("Arial", 0, 12));
        messageTextPanel.setLineWrap(true);
        messageTextPanel.setWrapStyleWord(true);
        scrollPane.setViewportView(messageTextPanel);

        messagePanel.add(scrollPane);

        getContentPane().add(messagePanel, new java.awt.GridBagConstraints());

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        postMessageButton.setFont(new java.awt.Font("Arial", 1, 12));
        postMessageButton.setText("Post Message");
        postMessageButton.setFocusCycleRoot(true);
        postMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postMessageButtonActionPerformed(evt);
            }
        });

        buttonsPanel.add(postMessageButton, new java.awt.GridBagConstraints());

        cancelButton.setFont(new java.awt.Font("Arial", 1, 12));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonsPanel.add(cancelButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(buttonsPanel, gridBagConstraints);

        pack();
    }//GEN-END:initComponents
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void postMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postMessageButtonActionPerformed
        // Add your handling code here:
        String message = messageTextPanel.getText();
        try {
            advUtils.createChatAdvertisement(parentPG, message);
            topFrame.refreshTreeWithNodeSelected();
            dispose();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_postMessageButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextArea messageTextPanel;
    private javax.swing.JButton postMessageButton;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
