/*
 * ListPage.java
 *
 * Created on December 10, 2003, 8:10 AM
 */

package dpm.dpmApp.desktop.subpages;

import dpm.content.DisplayUserObject;
import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.DpmPage;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import net.jxta.document.Advertisement;
import net.jxta.peergroup.PeerGroup;
import net.jxta.protocol.PeerAdvertisement;
import net.jxta.protocol.PeerGroupAdvertisement;



/** Page for showing simple lists of various items.
 * @author cumming
 * @since December 10, 2003, 8:10 AM
 */
public class ListPage extends DpmPage {
    protected DefaultListModel contentModel;
    
    /** Creates new form ListPage */
    public ListPage(String name, int jxtaType, DpmAppTopFrame topFrame, PeerGroup basePG) {
        super(name, jxtaType, topFrame, basePG); //super = DpmPage
        initComponents();
        this.contentModel = new DefaultListModel();
        contentDisplayList.setModel(contentModel);
        //this.searcher = new ContentSearcher(name, jxtaType, topFrame, this);
    }
    
    public void clear() {
        contentModel.clear();
    }
    
    public Advertisement getSelectedPeerAdv() {
        DisplayUserObject uo = (DisplayUserObject)contentDisplayList.getSelectedValue();
        //return (Advertisement)uo.getAdv();
        return null;
    }
    
    public void printSelectedAdv() {
        Advertisement adv = getSelectedPeerAdv();
        if(adv instanceof PeerAdvertisement) {
            PeerAdvertisement peerAdv = (PeerAdvertisement)adv;
            printMessage("Selected Peer name =  " + peerAdv.getName());     
        }
        else if(adv instanceof PeerGroupAdvertisement) {
            PeerGroupAdvertisement pgAdv = (PeerGroupAdvertisement)adv;
            printMessage("Selected Peergroup name =  " + pgAdv.getName());          
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPanel = new javax.swing.JScrollPane();
        contentDisplayList = new javax.swing.JList();

        setLayout(new java.awt.GridBagLayout());

        scrollPanel.setDoubleBuffered(true);
        scrollPanel.setFont(new java.awt.Font("Arial", 0, 12));
        scrollPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        scrollPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        contentDisplayList.setFont(new java.awt.Font("Arial", 0, 12));
        contentDisplayList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        contentDisplayList.setDoubleBuffered(true);
        scrollPanel.setViewportView(contentDisplayList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(scrollPanel, gridBagConstraints);

    }//GEN-END:initComponents
    
    /** Getter for property contentModel.
     * @return Value of property contentModel.
     *
     */
    public DefaultListModel getContentModel() {
        return contentModel;
    }
    
    /** Setter for property contentModel.
     * @param contentModel New value of property contentModel.
     *
     */
    public void setContentModel(DefaultListModel contentModel) {
        this.contentModel = contentModel;
    }
    
    /** Getter for property jxtaType.
     * @return Value of property jxtaType.
     *
     */
    public int getJxtaType() {
        return jxtaType;
    }
    
    /** Setter for property jxtaType.
     * @param jxtaType New value of property jxtaType.
     *
     */
    public void setJxtaType(int jxtaType) {
        this.jxtaType = jxtaType;
    }
    
    /** Getter for property contentDisplayList.
     * @return Value of property contentDisplayList.
     *
     */
    public JList getContentDisplayList() {
        return contentDisplayList;
    }
    
    /** Setter for property contentDisplayList.
     * @param contentDisplayList New value of property contentDisplayList.
     *
     */
    public void setContentDisplayList(JList contentDisplayList) {
        this.contentDisplayList = contentDisplayList;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList contentDisplayList;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
    
}
