/*
 * NewConstraintLinkForm.java
 *
 * Created on Sept 16, 2004
 */

package dpm.dpmApp.desktop.forms.links;

import dpm.content.DesignEntity;
import dpm.content.advertisement.AdvUtilities;
import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.forms.LinkForm;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import net.jxta.peergroup.PeerGroup;


/**
 *
 * @author  cumming
 */
public class NewChoicePointFormX extends LinkForm {
    
    /** Creates new form NewLinkForm */
    public NewChoicePointFormX(PeerGroup parentPG, DpmAppTopFrame topFrame) {
        super(parentPG, topFrame);
        AdvUtilities advUtils = topFrame.getAdvUtils();
        
        initComponents();
        this.sourcePage = addTreePage(sourcePanel, parentPG, ENTITIES);
        this.targetPage = addTreePage(targetPanel, parentPG, ENTITIES);
        this.sourceTree = sourcePage.getTree();
        this.targetTree = targetPage.getTree();
        
        addSourceTreeListener();
        addTargetTreeListener();
        setTransComboModel(sourceTransComboBox, sourcePage.getFirstDesignEntity());
        setTransComboModel(targetTransComboBox, targetPage.getFirstDesignEntity());
        
        topFrame.setPosition(this.getWidth(), this.getHeight(), this);
        pack();
        show();
    }
    
    /**When a source tree node is pressed */
    public void addSourceTreeListener() {
        sourceTree.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                // Add your handling code here:
                setTransComboModel(sourceTransComboBox, sourcePage.getSelectedDesignEntity());
            }
        });
    }
    
    /**When a target tree node is pressed */
    public void addTargetTreeListener() {
        targetTree.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                // Add your handling code here:
                setTransComboModel(targetTransComboBox, targetPage.getSelectedDesignEntity());
            }
        });
    }
    
    /**Used by both source and target entities */
    public void setTransComboModel(JComboBox comboBox, DesignEntity selEntity) {
        if(selEntity != null) {
            Set allTrans = selEntity.getLoopNetAdv().getTransitions();
            comboBox.setModel(new DefaultComboBoxModel(new Vector(allTrans)));
        }
        /**Else, nothing has been selected */
        else {
            Set emptySet = new HashSet();
            comboBox.setModel(new DefaultComboBoxModel(new Vector(emptySet)));
        }
        pack();
    }
    
    public String getTransitionSelected(JComboBox comboBox) {
        String trans = (String)comboBox.getSelectedItem();
        if(trans == null) {
            topFrame.showErrorDialog("Please select an existing transition", this);
            return null;
        }
        return trans;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        sourcePanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        sourceTransLabel = new javax.swing.JLabel();
        sourceTransComboBox = new javax.swing.JComboBox();
        targetTransLabel = new javax.swing.JLabel();
        targetTransComboBox = new javax.swing.JComboBox();
        cancelButton = new javax.swing.JButton();
        createChoicePointButton = new javax.swing.JButton();
        targetPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Constraint Link Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        sourcePanel.setBorder(new javax.swing.border.TitledBorder(null, "Entity to continue, if YES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(sourcePanel, new java.awt.GridBagConstraints());

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        sourceTransLabel.setFont(new java.awt.Font("Arial", 1, 12));
        sourceTransLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sourceTransLabel.setText("If YES, enable this transition");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 5, 0);
        buttonsPanel.add(sourceTransLabel, gridBagConstraints);

        sourceTransComboBox.setBackground(new java.awt.Color(255, 255, 255));
        sourceTransComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(sourceTransComboBox, gridBagConstraints);

        targetTransLabel.setFont(new java.awt.Font("Arial", 1, 12));
        targetTransLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        targetTransLabel.setText("if NO, enable this transition");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        buttonsPanel.add(targetTransLabel, gridBagConstraints);

        targetTransComboBox.setBackground(new java.awt.Color(255, 255, 255));
        targetTransComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        buttonsPanel.add(targetTransComboBox, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Arial", 1, 12));
        cancelButton.setText("Cancel / Close Window");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(cancelButton, gridBagConstraints);

        createChoicePointButton.setFont(new java.awt.Font("Arial", 1, 12));
        createChoicePointButton.setText("Create Choice Point");
        createChoicePointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createChoicePointButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(createChoicePointButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(buttonsPanel, gridBagConstraints);

        targetPanel.setBorder(new javax.swing.border.TitledBorder(null, "Entity to continue, if NO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(targetPanel, new java.awt.GridBagConstraints());

        pack();
    }//GEN-END:initComponents
    
    private void createChoicePointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createChoicePointButtonActionPerformed
        //Add your handling code here:
//        DesignEntity yesEntity = getSelectedEntity(sourcePage);
//        PeerGroup yesPG = getParentPG(sourcePage);
//        String yesTrans = getTransitionSelected(sourceTransComboBox);
//        
//        DesignEntity noEntity = getSelectedEntity(targetPage);
//        PeerGroup noPG = getParentPG(targetPage);
//        String noTrans = getTransitionSelected(targetTransComboBox);
//        
//        try {
//            if(sourceTargetOK(yesEntity, noEntity)) {
//                /**This creates YES and NO choicePointEntities, and all required constraint links */
//                advUtils.createChoicePointAdvertisements(yesEntity, yesPG, yesTrans, noEntity, noPG, noTrans);
//            }
//        }
//        catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_createChoicePointButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createChoicePointButton;
    private javax.swing.JPanel sourcePanel;
    private javax.swing.JComboBox sourceTransComboBox;
    private javax.swing.JLabel sourceTransLabel;
    private javax.swing.JPanel targetPanel;
    private javax.swing.JComboBox targetTransComboBox;
    private javax.swing.JLabel targetTransLabel;
    // End of variables declaration//GEN-END:variables
    
    
}
