/*
 * NewInfoLinkForm.java
 *
 * Created on Sept 16, 2004
 */

package dpm.dpmApp.desktop.forms.links;

import dpm.container.tree.PGTreeLeaf;
import dpm.content.DesignEntity;
import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.forms.LinkForm;
import dpm.dpmApp.desktop.subpages.PeerGroupsTreePage;
import java.util.HashSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import net.jxta.peergroup.PeerGroup;

/**
 *
 * @author  cumming
 */
public class NewInfoLinkForm extends LinkForm {
    
    /** Creates new form NewLinkForm */
    public NewInfoLinkForm(PeerGroup parentPG, DpmAppTopFrame topFrame) {
        super(parentPG, topFrame);
        
        initComponents();
        this.sourcePage = addTreePage(sourcePanel, parentPG, ENTITIES);
        this.targetPage = addTreePage(targetPanel, parentPG, ENTITIES);
        this.sourceTree = sourcePage.getTree();
        this.targetTree = targetPage.getTree();
        
        /**If a doBefore form, then the link type is fixed as 'doBefore' */
        setConstraintNameComboModel();
        topFrame.setPosition(this.getWidth(), this.getHeight(), this);
        pack();
        show();
    }
    
    public void setConstraintNameComboModel() {
        /** Gets all the appropriate role names */
        HashSet conNames = getConstraintNames();
        linkTypeComboBox.setModel(new DefaultComboBoxModel(new Vector(conNames)));
    }
    
    /**Used at the end to construct the link */
    public String getLinkType() {
        String linkType = (String)linkTypeComboBox.getSelectedItem();
        if(linkType == null) {
            topFrame.showErrorDialog("Please select an existing link type, or create a new one", this);
            return null;
        }
        return linkType;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        sourcePanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        linkTypeLabel1 = new javax.swing.JLabel();
        linkTypeLabel2 = new javax.swing.JLabel();
        linkTypeComboBox = new javax.swing.JComboBox();
        cancelButton = new javax.swing.JButton();
        linkSourceToTargetButton = new javax.swing.JButton();
        targetPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Information Link Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        sourcePanel.setBorder(new javax.swing.border.TitledBorder(null, "Select Source", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(sourcePanel, new java.awt.GridBagConstraints());

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        linkTypeLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        linkTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkTypeLabel1.setLabelFor(linkTypeComboBox);
        linkTypeLabel1.setText("Select Existing, or");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(linkTypeLabel1, gridBagConstraints);

        linkTypeLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        linkTypeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        linkTypeLabel2.setText("Create New Link Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        buttonsPanel.add(linkTypeLabel2, gridBagConstraints);

        linkTypeComboBox.setEditable(true);
        linkTypeComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(linkTypeComboBox, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Arial", 1, 12));
        cancelButton.setText("Cancel / Close Window");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(cancelButton, gridBagConstraints);

        linkSourceToTargetButton.setFont(new java.awt.Font("Arial", 1, 12));
        linkSourceToTargetButton.setText("Link Source > Target");
        linkSourceToTargetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkSourceToTargetButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(linkSourceToTargetButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(buttonsPanel, gridBagConstraints);

        targetPanel.setBorder(new javax.swing.border.TitledBorder(null, "Select Target", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(targetPanel, new java.awt.GridBagConstraints());

        pack();
    }//GEN-END:initComponents
    
    private void linkSourceToTargetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkSourceToTargetButtonActionPerformed
        // Add your handling code here:
        DesignEntity sourceEntity = getSelectedEntity(sourcePage);
        DesignEntity targetEntity = getSelectedEntity(targetPage);
        PeerGroup sourcePG = getParentPG(sourcePage);
        PeerGroup targetPG = getParentPG(targetPage);
        String constraintName = getLinkType();
        
        try {
            /**Provides very basic error checking */
            if(sourceTargetOK(sourceEntity, targetEntity)) {
                /** Creates a linkAdv and publishes it [locally] in the parentPG */
                advUtils.createLinkAdvertisement
                (sourceEntity, targetEntity, constraintName, NOT_RELEVANT, NOT_RELEVANT, sourcePG, targetPG);
                topFrame.refreshTreeWithNodeSelected();
                //this.dispose();
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_linkSourceToTargetButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton linkSourceToTargetButton;
    private javax.swing.JComboBox linkTypeComboBox;
    private javax.swing.JLabel linkTypeLabel1;
    private javax.swing.JLabel linkTypeLabel2;
    private javax.swing.JPanel sourcePanel;
    private javax.swing.JPanel targetPanel;
    // End of variables declaration//GEN-END:variables
    
    
}
