/*
 * NewConstraintLinkForm.java
 *
 * Created on Sept 16, 2004
 */

package dpm.dpmApp.desktop.forms.links;

import dpm.content.DesignEntity;
import dpm.content.advertisement.designEntity.related.constraint.LinkAdvertisement;
import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.forms.LinkForm;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import net.jxta.peergroup.PeerGroup;


/**
 *
 * @author  cumming
 */
public class NewSequentialLinkForm extends LinkForm {
    
    /** Creates new form NewLinkForm */
    public NewSequentialLinkForm(PeerGroup parentPG, DpmAppTopFrame topFrame) {
        super(parentPG, topFrame);
        
        initComponents();
        this.sourcePage = addTreePage(sourcePanel, parentPG, ENTITIES);
        this.targetPage = addTreePage(targetPanel, parentPG, ENTITIES);
        this.sourceTree = sourcePage.getTree();
        this.targetTree = targetPage.getTree();
        
        addSourceTreeListener();
        addTargetTreeListener();
        //setSourceStateComboModel(sourcePage.getFirstDesignEntity());
        //setTargetTransComboModel(targetPage.getFirstDesignEntity());
        
        //linkTypeLabel.setText("Link Type: " + DO_BEFORE);
        topFrame.setPosition(this.getWidth(), this.getHeight(), this);
        pack();
        show();
    }
    
    /**When a source tree node is pressed */
    public void addSourceTreeListener() {
        sourceTree.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                // Add your handling code here:
                //setSourceStateComboModel(sourcePage.getSelectedDesignEntity());
            }
        });
    }
    
    /**When a target tree node is pressed */
    public void addTargetTreeListener() {
        targetTree.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                // Add your handling code here:
                //System.out.println("target tree pressed");
                //setTargetTransComboModel(targetPage.getSelectedDesignEntity());
            }
        });
    }
    
    //public String getDoFirstEndState(
    
    
    
    //    public void setSourceStateComboModel(DesignEntity selEntity) {
    //        if(selEntity != null) {
    //            Set allStates = selEntity.getLoopNetAdv().getStates();
    //            sourceStateComboBox.setModel(new DefaultComboBoxModel(new Vector(allStates)));
    //        }
    //        /**Else, nothing has been selected */
    //        else {
    //            Set emptySet = new HashSet();
    //            sourceStateComboBox.setModel(new DefaultComboBoxModel(new Vector(emptySet)));
    //        }
    //        pack();
    //    }
    
    //    public void setTargetTransComboModel(DesignEntity selEntity) {
    //        /** Gets all the appropriate transition names */
    //        if(selEntity != null) {
    //            Set allTrans = selEntity.getLoopNetAdv().getTransitions();
    //            targetTransComboBox.setModel(new DefaultComboBoxModel(new Vector(allTrans)));
    //        }
    //        /**Else, nothing has been selected */
    //        else {
    //            Set emptySet = new HashSet();
    //            targetTransComboBox.setModel(new DefaultComboBoxModel(new Vector(emptySet)));
    //        }
    //        pack();
    //    }
    
    //    public String getSourceState() {
    //        String sourceState = (String)sourceStateComboBox.getSelectedItem();
    //        if(sourceState == null) {
    //            topFrame.showErrorDialog("Please select an existing state", this);
    //            return null;
    //        }
    //        return sourceState;
    //    }
    
    //    public String getTargetTransition() {
    //        String targetTrans = (String)targetTransComboBox.getSelectedItem();
    //        if(targetTrans == null) {
    //            topFrame.showErrorDialog("Please select an existing transition", this);
    //            return null;
    //        }
    //        return targetTrans;
    //    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        sourcePanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        linkSourceToTargetButton = new javax.swing.JButton();
        targetPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Sequential Link Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        sourcePanel.setBorder(new javax.swing.border.TitledBorder(null, "Select Source", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(sourcePanel, new java.awt.GridBagConstraints());

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        cancelButton.setFont(new java.awt.Font("Arial", 1, 12));
        cancelButton.setText("Cancel / Close Window");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(cancelButton, gridBagConstraints);

        linkSourceToTargetButton.setFont(new java.awt.Font("Arial", 1, 12));
        linkSourceToTargetButton.setText("Link DoFirst > DoSecond");
        linkSourceToTargetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkSourceToTargetButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(linkSourceToTargetButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(buttonsPanel, gridBagConstraints);

        targetPanel.setBorder(new javax.swing.border.TitledBorder(null, "Select Target", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(targetPanel, new java.awt.GridBagConstraints());

        pack();
    }//GEN-END:initComponents
    
    private void linkSourceToTargetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkSourceToTargetButtonActionPerformed
        // Add your handling code here:
        DesignEntity doFirstEntity = getSelectedEntity(sourcePage);
        DesignEntity doSecondEntity = getSelectedEntity(targetPage);
        PeerGroup sourcePG = getParentPG(sourcePage);
        PeerGroup targetPG = getParentPG(targetPage);
        /**The state that must be reached before doSecondEntity can start */
        String doFirstEndState = doFirstEntity.getLoopNetAdv().getLastState();
        /**The transition that the doSecondEntity can't get past before completion of doFirstEntity */
        String doSecondTrans = doSecondEntity.getLoopNetAdv().getFirstTransition();
        
        try {
            if(sourceTargetOK(doFirstEntity, doSecondEntity)) {
                /** Creates a linkAdv and publishes it [locally] in the parentPG */
                LinkAdvertisement newSeqLink = advUtils.createLinkAdvertisement
                (doFirstEntity, doSecondEntity, DO_BEFORE, doFirstEndState, doSecondTrans, sourcePG, targetPG);
                topFrame.refreshTreeWithNodeSelected();
                //this.dispose();
                
                /**If new sub entity can be created: does not conflict logically with existing ones */
//                if (newSeqLink != null) {
//                     /**Second, create an information link that points from the parent to the subentity */
//                    advUtils.createLinkAdvertisement(
//                    doFirstEntity, doSecondEntity, SEQ_ENTITY, NOT_RELEVANT, NOT_RELEVANT, sourcePG, targetPG);
//                }
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_linkSourceToTargetButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton linkSourceToTargetButton;
    private javax.swing.JPanel sourcePanel;
    private javax.swing.JPanel targetPanel;
    // End of variables declaration//GEN-END:variables
    
    
}
