/*
 * NewLinkForm.java
 *
 * Created on March 10, 2004, 2:23 PM
 */

package dpm.dpmApp.desktop.forms.links;

import dpm.content.DesignEntity;
import dpm.content.advertisement.designEntity.related.constraint.LinkAdvertisement;
import dpm.dpmApp.desktop.DpmAppTopFrame;
import dpm.dpmApp.desktop.forms.LinkForm;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import net.jxta.peergroup.PeerGroup;


/**
 * A form for creating the links needed for a entity-subentity relation
 * @author  cumming
 */
public class NewSequentialLinkChildOnlyForm extends LinkForm {
    DesignEntity parentEntity;
    String parentName;
    
    /** Creates new form NewLinkForm */
    public NewSequentialLinkChildOnlyForm(DesignEntity parentEntity, PeerGroup parentPG, DpmAppTopFrame topFrame) {
        super(parentPG, topFrame);
        this.parentEntity = parentEntity;
        this.parentName = parentEntity.getFullName();
        
        initComponents();
        super.setTitle("Sequential Link Form with " + parentName + " as Parent");
        
        parentNameLabel.setText("Parent entity");
        parentNameField.setText(" " + parentName);
        parentStateLabel.setText("Current state");
        parentStateField.setText(parentEntity.getCurrentState());
        
        linkSourceToTargetButton.setText("Link " + parentName + " > Child");
        targetTransLabel.setText("Completion of Child allows");
        targetTransLabel1.setText(parentName + " to continue");
        
        this.targetPage = addTreePage(targetPanel, parentPG, ENTITIES);
        this.targetTree = targetPage.getTree();
        
        topFrame.setPosition(this.getWidth(), this.getHeight(), this);
        pack();
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonsPanel = new javax.swing.JPanel();
        parentNameLabel = new javax.swing.JLabel();
        parentNameField = new javax.swing.JTextField();
        parentStateLabel = new javax.swing.JLabel();
        parentStateField = new javax.swing.JTextField();
        targetTransLabel = new javax.swing.JLabel();
        targetTransLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        linkSourceToTargetButton = new javax.swing.JButton();
        targetPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Sub-Entity Link Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        parentNameLabel.setFont(new java.awt.Font("Arial", 1, 12));
        parentNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentNameLabel.setText("Parent name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonsPanel.add(parentNameLabel, gridBagConstraints);

        parentNameField.setEditable(false);
        parentNameField.setFont(new java.awt.Font("Arial", 0, 12));
        parentNameField.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonsPanel.add(parentNameField, gridBagConstraints);

        parentStateLabel.setFont(new java.awt.Font("Arial", 1, 12));
        parentStateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parentStateLabel.setText("Parent state");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonsPanel.add(parentStateLabel, gridBagConstraints);

        parentStateField.setEditable(false);
        parentStateField.setFont(new java.awt.Font("Arial", 0, 12));
        parentStateField.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        buttonsPanel.add(parentStateField, gridBagConstraints);

        targetTransLabel.setFont(new java.awt.Font("Arial", 1, 12));
        targetTransLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        targetTransLabel.setText("Completion of Child allows");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(targetTransLabel, gridBagConstraints);

        targetTransLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        targetTransLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        targetTransLabel1.setText("Parent to continue");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        buttonsPanel.add(targetTransLabel1, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Arial", 1, 12));
        cancelButton.setText("Cancel / Close Window");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(cancelButton, gridBagConstraints);

        linkSourceToTargetButton.setFont(new java.awt.Font("Arial", 1, 12));
        linkSourceToTargetButton.setText("Link Parent > Child");
        linkSourceToTargetButton.setMaximumSize(new java.awt.Dimension(163, 25));
        linkSourceToTargetButton.setMinimumSize(new java.awt.Dimension(163, 25));
        linkSourceToTargetButton.setPreferredSize(new java.awt.Dimension(163, 25));
        linkSourceToTargetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkSourceToTargetButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        buttonsPanel.add(linkSourceToTargetButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(buttonsPanel, gridBagConstraints);

        targetPanel.setBorder(new javax.swing.border.TitledBorder(null, "Select Child", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        getContentPane().add(targetPanel, new java.awt.GridBagConstraints());

        pack();
    }//GEN-END:initComponents
    
    private void linkSourceToTargetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkSourceToTargetButtonActionPerformed
        // Add your handling code here:
        DesignEntity doSecondEntity = getSelectedEntity(targetPage);
        PeerGroup targetPG = getParentPG(targetPage);
        /**The state that must be reached before doSecondEntity can start */
        String doFirstEndState = parentEntity.getLoopNetAdv().getLastState();
        /**The transition that the doSecondEntity can't get past before completion of doFirstEntity */
        String doSecondTrans = doSecondEntity.getLoopNetAdv().getFirstTransition();
        
        try {
            if(sourceTargetOK(parentEntity, doSecondEntity)) {
                /** Creates a linkAdv and publishes it [locally] in the parentPG */
                LinkAdvertisement newSeqLink = advUtils.createLinkAdvertisement
                (parentEntity, doSecondEntity, DO_BEFORE, doFirstEndState, doSecondTrans, parentPG, targetPG);
                topFrame.refreshTreeWithLeafSelected();
                this.dispose();
                
                /**If new sub entity can be created: does not conflict logically with existing ones */
//                if (newSeqLink != null) {
//                     /**Second, create an information link that points from the parent to the subentity */
//                    advUtils.createLinkAdvertisement(
//                    parentEntity, doSecondEntity, SEQ_ENTITY, NOT_RELEVANT, NOT_RELEVANT, parentPG, targetPG);
//                }
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_linkSourceToTargetButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton linkSourceToTargetButton;
    private javax.swing.JTextField parentNameField;
    private javax.swing.JLabel parentNameLabel;
    private javax.swing.JTextField parentStateField;
    private javax.swing.JLabel parentStateLabel;
    private javax.swing.JPanel targetPanel;
    private javax.swing.JLabel targetTransLabel;
    private javax.swing.JLabel targetTransLabel1;
    // End of variables declaration//GEN-END:variables
    
    
}
