/*
 * PolicyInputPanel.java
 *
 * Created on February 28, 2004, 11:29 AM
 */

package dpm.dpmApp.desktop.forms.input.panels;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import dpm.content.state.*;
import dpm.content.advertisement.*;
import dpm.content.advertisement.net.*;
import dpm.content.advertisement.designEntity.*;
import dpm.content.advertisement.designEntity.related.*;
import dpm.content.*;
import dpm.dpmApp.desktop.*;
import dpm.dpmApp.desktop.forms.input.*;


/**
 *
 * @author  mc9p
 */
public class PolicyInputPanelAdd extends TransitionInputPanel {
    
    /** Creates new form PolicyInputPanel */
    /** NOTE: one for each transition */
    public PolicyInputPanelAdd(String transName, Set roles) {
        super(transName);
        setUpInputSetIterator(roles);
        initComponents();
        setUpPanel();
    }
    
    /**Adds labels showing existing roles, and a textField for users to add new roles */
    private void setUpPanel() {
        addTransitionHeader();
        if(inputSetEmpty) {
            addOnePlainLabel("No existing input suggestions for this transition");
        }
        else {
            addOnePlainLabel("Previously specified inputs required from these roles:");
            /**add labels listing existing roles */
            for(Iterator i = inputSetIterator; i.hasNext(); ) {
                String roleName = (String)i.next();
                if(!roleName.equals(EMPTY_STRING)) {
                    addOnePlainLabel("> " + roleName);
                }
            }
        }
        addOneTextInputField();
    }
    
    /**Retrieves input only from text field */
    public Set getAllUserInput() {
        Set result = new HashSet();
        Set textInput = getTextInputStringSet();
        /** all additional roles added to text field */
        if(textInput != null) {
            result.addAll(textInput);
        }
        return result;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridLayout(0, 1));

        setName("PolicyInputPanel");
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
}
