/*
 * PolicyInputPanelDelete.java
 *
 * Created on Oct 12, 2004
 */

package dpm.dpmApp.desktop.forms.input.panels;

import dpm.dpmApp.desktop.forms.input.TransitionInputPanel;
import java.awt.Component;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JCheckBox;


/**
 *
 * @author  mc9p
 */
public class PolicyInputPanelDelete extends TransitionInputPanel {    
    
    /** Creates new form PolicyInputPanel */
    /** NOTE: one for each transition */
    public PolicyInputPanelDelete(String transName, Set roles) {
        super(transName);
        setUpInputSetIterator(roles);
        initComponents();
        setUpPanel();
    }
    
    /**Add checks boxes for all existing roles names (to delete) */
    private void setUpPanel() {
        addTransitionHeader();
        if(inputSetEmpty) {
            addOnePlainLabel("No policies discovered for this transition");
            return;
        }
        addOnePlainLabel("Select roles to delete for this transition:");
        /**Default is not to select anything (to delete) */
        boolean checked = false;
        for(Iterator i = inputSetIterator; i.hasNext(); ) {
            String roleName = (String)i.next();
            if(roleName != null) {
                /**add unchecked boxes */
                addOneCheckBox(roleName, null, checked);
            }
        }
    }
    
    /**Input are the names of the check boxes that are NOT checked */
    public Set getAllUserInput() {
        return getAllUnCheckedInput();
    }
    
    public Set getAllRolesToKeep() {
        return getAllUnCheckedInput();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridLayout(0, 1));

        setName("PolicyInputPanel");
    }//GEN-END:initComponents
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
}
