/*
 * PolicyInputPanel.java
 *
 * Created on February 28, 2004, 11:29 AM
 */

package dpm.dpmApp.desktop.forms.input.panels;

import dpm.dpmApp.desktop.forms.input.TransitionInputPanel;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;


/**
 *
 * @author  mc9p
 */
public class PolicyInputPanelNewEntity extends TransitionInputPanel {
 
    /**One panel constructed for each transition */
    public PolicyInputPanelNewEntity(String transName, Set roles) {
        super(transName);
        setUpInputSetIterator(roles);
        initComponents();
        setUpPanel();
    }
    
    /**Adds check boxes showing suggested roles, and a textField for users to add new roles */
    private void setUpPanel() {
        addTransitionHeader();
        if(inputSetEmpty)  {
            addOnePlainLabel("No input suggestions for this transition");
        }
        else {
            addOnePlainLabel("Select role inputs needed for this transition:");
            boolean checked = true;
            for(Iterator i = inputSetIterator; i.hasNext(); ) {
                String roleName = (String)i.next();
                if(!roleName.equals(EMPTY_STRING)) {
                    addOneCheckBox(roleName, null, checked);
                }
            }
        }
        addOneTextInputField();
    }
    
    /**Retrieves input from both check boxes and text field */
    public Set getAllUserInput() {
        Set result = new HashSet();
        /** all roles checked */
        Set cbInput = getAllCheckedInput();
        if(cbInput != null) {
            result.addAll(cbInput);
        }
        Set textInput = getTextInputStringSet();
        /** all additional roles added to text field */
        if(textInput != null) {
            result.addAll(textInput);
        }
        return result;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridLayout(0, 1));

        setName("PolicyInputPanel");
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
}
